### ISSUE TITLE
A couple of small doc update suggestions/questions

### ISSUE THREAD

**Issue by tensafefrogs** [alessandrokonrad/Pi-Pool#7]
Hi, as I'm reading your docs and considering building one of these, I have a couple of questions/notes about your instructions:

1) Your recommended SATA cable is on the "naughty list"[1] on the site you link to with the following note: "Despite earlier reports as working Ryan and one other have reported this adapter does not work unless you enable quirks mode! Don’t make Ryan’s sacrifice in vain and avoid this one." - should your recommendation be updated to one of the adapters on the known goog list?

2) It appears that booting from USB is now officially supported by Raspberry Pi 4, so you may be able to remove the MicroSD card requirement, or at least add a note that this is now built-in behavior. Also [1]

[1] https://jamesachambers.com/raspberry-pi-4-usb-boot-config-guide-for-ssd-flash-drives/

Cheers and thanks for the guide!

**Comment by alessandrokonrad** [comment]
Hey thank you for sharing these notes.
 
I wasn't aware of the updated usb boot guide. I'm actually using the the adapter of the naughty list. It works pretty well and it was before not listed there, so that confuses me. Anyway as more adapters than just mine work I'll just keep it general and just share the link to working adapters.

Yes I heared that too that new Pis will come with USB booting preflashed. Will adjust that as well.
